# imports

In [2]:
import pandas as pd

# Vectors comp

In [ ]:
vectors_gpt_5_mini_and_gpt_5 = pd.read_csv('data/vector_score_2_comparison.csv')

In [ ]:
vectors_gpt_5_mini_and_gpt_5.shape

(175, 7)

In [ ]:
vectors_gpt_5_mini_and_gpt_5

,query_id,candidate_id,search_system,relevance_score_gpt_5_mini,judge_comment_gpt_5_mini,relevance_score_gpt_5,judge_comment_gpt_5
0,Q_00001,C_15656,vector,2.0,"Опытный Python-разработчик, есть бэкенд-опыт (...",0.0,Требуется строго офис в Зеленограде и стек Fas...
1,Q_00001,C_38834,vector,2.0,"Есть опыт Python, Django/DRF, REST, готов к пе...",2.0,Роль Python backend совпадает; Django подтверж...
2,Q_00001,C_30875,vector,2.0,"Сильный Python backend (8+ лет), готов к перее...",0.0,Требуются Python + FastAPI/Django и работа на ...
3,Q_00012,C_29752,vector,2.0,"Соответствует: многолетний опыт QA, есть ручно...",2.0,"QA (ручное+авто) подтверждено: 6+ лет QA, 2 го..."
4,Q_00012,C_32960,vector,2.0,Соответствует: опыт QA/авто-тестирования 7+ ле...,0.0,"Роль и опыт QA соответствуют, но кандидат орие..."
...,...,...,...,...,...,...,...
170,Q_00139,C_35309,vector,2.0,"Соответствует — опыт QA 2 года 8 мес, работа у...",1.0,"Роль QA и опыт (2.8 года) совпадают, формат уд..."
171,Q_00139,C_04782,vector,2.0,Соответствует: опыт ~2.8 года в QA (ручное и а...,2.0,Профиль QA automation: есть ручное тестировани...
172,Q_00142,C_06852,vector,2.0,"Подходит — 3+ года фронтенд, JS/TS, архитектур...",0.0,Нет подтверждения ключевого стека: React (web)...
173,Q_00142,C_44022,vector,2.0,"Богатый фронтенд-опыт (JS, указаны React/Vue),...",1.0,"Frontend/React подтвержден, опыт и участие в а..."
174,Q_00142,C_40625,vector,2.0,Соответствует требованиям — большой опыт фронт...,1.0,"Роль frontend совпадает, есть JS и упоминание ..."

In [7]:
candidates = pd.read_csv('../prepared/pooled_candidates.csv')
queries = pd.read_csv('../prepared/queries.csv')

In [8]:
queries = queries[['query_id', 'job_title', 'query_text']]

In [ ]:
data_check = (
    vectors_gpt_5_mini_and_gpt_5
    .merge(queries, on='query_id', how='left')
    .merge(candidates, on='candidate_id', how='left')
    )

data_check = data_check[data_check['relevance_score_gpt_5'] == 2]
data_check.reset_index(drop=True).to_excel('data/vectors_2.xlsx', index=False)

# GPT 5 sample judge

In [8]:
data = pd.read_csv('data/judgments_test_sample_200_rows_GPT5.csv')
candidates = pd.read_csv('../prepared/pooled_candidates.csv')
queries = pd.read_csv('../prepared/queries.csv')

pd.set_option('display.max_colwidth', None)

In [30]:
queries[queries['query_id'] == 'Q_00041']

,query_id,vacancy_id,job_title,domain,query_type,query_text
40,Q_00041,VAC_0001,Backend-разработчик,backend,normal,"Backend-разработчик на Python (FastAPI/Django), опыт 1-3 года, на месте, Зеленоград"

In [31]:
candidates[candidates['candidate_id'] == 'C_15523']

,candidate_id,sex,age,expected_salary_rub,desired_position,city,ready_to_relocate,ready_for_business_trips,employment_type,work_schedule,work_experience,work_experience_years,last_company,last_job_title,education_level_and_university,resume_updated_at,has_car
2038,C_15523,Мужчина,26,30000,junior python developer,Воронеж,True,True,"стажировка, частичная занятость, проектная работа, полная занятость","гибкий график, полный день, сменный график, удаленная работа","Опыт работы 2 года 11 месяцев Март 2019 — по настоящее время 3 месяца ООО ИТ-РУСС Воронеж , www.it-russ.com Django Python developer Django Python developer Декабрь 2017 — Декабрь 2018 1 год 1 месяц Военный инновационный технополис ЭРА Анапа , www.era-tehnopolis.ru/ Старший оператор научной роты Проходил срочную службу на должности старшего оператора научной роты в ВИТ ""Эра"". Занимался программированием на языке Java, Matlab Январь 2016 — Февраль 2017 1 год 2 месяца АО ОТ-ОЙЛ Воронеж , www.ot-oil.ru Информационные технологии, системная интеграция, интернет ... Системная интеграция, автоматизации технологических и бизнес-процессов предприятия, ИТ-консалтинг Специалист сектора интеграции (Oracle) Разработка процедур, функций, пакетов. Настройка интеграции данных, первоначальное наполнение баз данных - Решение проблем и задач интеграции на этапе технической поддержки системы; - Формирование технического задания на интеграцию данных; - Настройка интеграции данных между информационными системами (АТОЛЛ Интегратор). Декабрь 2014 — Апрель 2015 5 месяцев AT Consulting Воронеж , www.at-consulting.ru Информационные технологии, системная интеграция, интернет ... Разработка программного обеспечения Системная интеграция, автоматизации технологических и бизнес-процессов предприятия, ИТ-консалтинг Аналитик Аналитическая деятельность: -Анализ задачи, формирование алгоритмов решения тех или иных проблем; -Работа с документацией: формирование, написание и редактирование технических заданий, функциональных требований; -Написание скриптов проверки данных.",2.916667,ООО ИТ-РУСС,Django Python developer,"Высшее образование (Магистр) 2017 Воронежский государственный университет, Воронеж Факультет прикладной математики, информатики и механики, Математическое обеспечение и администрирование информационных систем 2015 Воронежский государственный университет, Воронеж Факультет прикладной математики, информатики и механики, Математическое обеспечение и администрирование информационных систем",2019-05-12 19:29:00,False