In [17]:
import pandas as pd

In [19]:
retrieval_vector = pd.read_csv('emb/retrieval_vector.csv')
bm25 = pd.read_csv('bm25/retrieval_bm25.csv')
queries = pd.read_csv('prepared/queries.csv')
sql_hr = pd.read_csv('sql-hr/retrieval_sql_hr.csv')

# sql_hr = sql_hr.drop(columns=['query_id'], axis=1)
# sql_hr = sql_hr.merge(queries[['query_id', 'query_text']], on='query_text', how='inner')

In [20]:
sql_hr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2267 entries, 0 to 2266
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   query_id             2267 non-null   object
 1   candidate_id         2267 non-null   object
 2   search_system        2267 non-null   object
 3   rank                 2267 non-null   int64
 4   score                2267 non-null   float64
 5   latency_to_first_ms  2267 non-null   int64
 6   latency_ms           2267 non-null   int64
 7   retrieved_at         2267 non-null   object
dtypes: float64(1), int64(3), object(4)
memory usage: 141.8+ KB

In [49]:
retrieval_vector.columns

Index(['query_id', 'candidate_id', 'search_system', 'rank', 'score',
       'latency_ms', 'retrieved_at'],
      dtype='object')

In [50]:
bm25.columns

Index(['query_id', 'candidate_id', 'search_system', 'rank', 'score',
       'latency_ms', 'retrieved_at'],
      dtype='object')

In [51]:
sql_hr.columns

Index(['query_id', 'query_text', 'candidate_id', 'search_system', 'rank',
       'score', 'latency_to_first_ms', 'latency_ms', 'full_latency_ms',
       'retrieved_at'],
      dtype='object')

In [52]:
sql_hr_cols = sql_hr[[
    'query_id',
    'candidate_id',
    'search_system',
    'rank',
    'score',
    'latency_to_first_ms',
    'latency_ms',
    'retrieved_at'
    ]]

In [53]:
sql_hr_cols.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2195 entries, 0 to 2194
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   query_id             2195 non-null   object
 1   candidate_id         2195 non-null   object
 2   search_system        2195 non-null   object
 3   rank                 2195 non-null   int64
 4   score                2180 non-null   float64
 5   latency_to_first_ms  2195 non-null   int64
 6   latency_ms           2195 non-null   int64
 7   retrieved_at         2195 non-null   object
dtypes: float64(1), int64(3), object(4)
memory usage: 137.3+ KB

In [54]:
retrieval_vector.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2400 entries, 0 to 2399
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   query_id       2400 non-null   object
 1   candidate_id   2400 non-null   object
 2   search_system  2400 non-null   object
 3   rank           2400 non-null   int64
 4   score          2400 non-null   float64
 5   latency_ms     2400 non-null   float64
 6   retrieved_at   2400 non-null   object
dtypes: float64(2), int64(1), object(4)
memory usage: 131.4+ KB

In [55]:
bm25.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2400 entries, 0 to 2399
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   query_id       2400 non-null   object
 1   candidate_id   2400 non-null   object
 2   search_system  2400 non-null   object
 3   rank           2400 non-null   int64
 4   score          2400 non-null   float64
 5   latency_ms     2400 non-null   float64
 6   retrieved_at   2400 non-null   object
dtypes: float64(2), int64(1), object(4)
memory usage: 131.4+ KB

In [60]:
sql_hr_cols[100:105]

,query_id,candidate_id,search_system,rank,score,latency_to_first_ms,latency_ms,retrieved_at
100,Q_00008,C_15712,sql_hr,11,1.765832,36350,92436,2026-03-29T01:33:19.169998+00:00
101,Q_00008,C_21624,sql_hr,12,1.630247,36350,92436,2026-03-29T01:33:19.169998+00:00
102,Q_00008,C_26932,sql_hr,13,1.590079,36350,92436,2026-03-29T01:33:19.169998+00:00
103,Q_00008,C_40954,sql_hr,14,1.511344,36350,92436,2026-03-29T01:33:19.169998+00:00
104,Q_00008,C_31852,sql_hr,15,1.491120,36350,92436,2026-03-29T01:33:19.169998+00:00

In [25]:
queries = pd.read_csv('prepared/queries.csv')
candidates = pd.read_csv('raw/candidates.csv')

In [61]:
queries[queries['query_id'] == 'Q_00008'].head()

,query_id,vacancy_id,job_title,domain,query_type,query_text
7,Q_00008,VAC_0008,Backend-разработчик (Java/Kotlin),backend,strict,"Backend-разработчик (Java/Kotlin), опыт 3-6 ле..."

In [62]:
candidates[candidates['candidate_id'] == 'C_15712']

,candidate_id,sex,age,expected_salary_rub,desired_position,city,ready_to_relocate,ready_for_business_trips,employment_type,work_schedule,work_experience,work_experience_years,last_company,last_job_title,education_level_and_university,resume_updated_at,has_car
15711,C_15712,Мужчина,43,250000,Программист-разработчик,Москва,False,False,полная занятость,полный день,Опыт работы 16 лет 10 месяцев Программист-раз...,16.833333,ПРОФ-ИТ ГРУПП,Программист-разработчик,Высшее образование 1997 Челябинский металлурги...,2019-01-30 10:37:00,False

In [63]:
sql_hr_cols.to_csv('sql-hr/retrieval_sql_hr.csv', index=False)

In [27]:
queries[queries['query_id'] == 'Q_00008']

,query_id,vacancy_id,job_title,domain,query_type,query_text
7,Q_00008,VAC_0008,Backend-разработчик (Java/Kotlin),backend,strict,"Backend-разработчик (Java/Kotlin), опыт 3-6 ле..."

In [26]:
candidates[candidates['candidate_id'] == 'C_05390']

,candidate_id,sex,age,expected_salary_rub,desired_position,city,ready_to_relocate,ready_for_business_trips,employment_type,work_schedule,work_experience,work_experience_years,last_company,last_job_title,education_level_and_university,resume_updated_at,has_car
5389,C_05390,Мужчина,30,180000,Ведущий Backend-разработчик (PHP) / TeamLead,Санкт-Петербург,True,True,полная занятость,полный день,Опыт работы 11 лет 6 месяцев Ведущий Backend-...,11.5,Корпорация Сибирское здоровье,Руководитель обособленного отдела веб-разработки,Высшее образование 2013 Московский технически...,2019-04-25 11:36:00,False

In [23]:
sql_hr[sql_hr['query_id'] == 'Q_00008']

,query_id,candidate_id,search_system,rank,score,latency_to_first_ms,latency_ms,retrieved_at
94,Q_00008,C_05390,sql_hr,1,5.360648,49597,129015,2026-04-02T21:45:15.621914+00:00
95,Q_00008,C_18361,sql_hr,2,5.232892,49597,129015,2026-04-02T21:45:15.621914+00:00
96,Q_00008,C_13564,sql_hr,3,4.790746,49597,129015,2026-04-02T21:45:15.621914+00:00
97,Q_00008,C_19292,sql_hr,4,4.761497,49597,129015,2026-04-02T21:45:15.621914+00:00
98,Q_00008,C_08927,sql_hr,5,4.552195,49597,129015,2026-04-02T21:45:15.621914+00:00
99,Q_00008,C_03634,sql_hr,6,4.546404,49597,129015,2026-04-02T21:45:15.621914+00:00
100,Q_00008,C_12363,sql_hr,7,4.284947,49597,129015,2026-04-02T21:45:15.621914+00:00
101,Q_00008,C_18527,sql_hr,8,4.117008,49597,129015,2026-04-02T21:45:15.621914+00:00
102,Q_00008,C_23202,sql_hr,9,4.077612,49597,129015,2026-04-02T21:45:15.621914+00:00
103,Q_00008,C_03202,sql_hr,10,4.065489,49597,129015,2026-04-02T21:45:15.621914+00:00
104,Q_00008,C_12426,sql_hr,11,4.028575,49597,129015,2026-04-02T21:45:15.621914+00:00
105,Q_00008,C_24236,sql_hr,12,3.792846,49597,129015,2026-04-02T21:45:15.621914+00:00
106,Q_00008,C_14428,sql_hr,13,3.706415,49597,129015,2026-04-02T21:45:15.621914+00:00
107,Q_00008,C_28452,sql_hr,14,3.648914,49597,129015,2026-04-02T21:45:15.621914+00:00
108,Q_00008,C_18212,sql_hr,15,3.505267,49597,129015,2026-04-02T21:45:15.621914+00:00