In [18]:
import pandas as pd

In [43]:
retrieval_vector = pd.read_csv('emb/retrieval_vector.csv')
bm25 = pd.read_csv('bm25/retrieval_bm25.csv')
queries = pd.read_csv('prepared/queries.csv')
sql_hr_bigger = pd.read_csv('sql-hr/retrieval_sql_hr_bigger_llm_new.csv')

# sql_hr = sql_hr.drop(columns=['query_id'], axis=1)
# sql_hr = sql_hr.merge(queries[['query_id', 'query_text']], on='query_text', how='inner')

In [44]:
sql_hr_bigger.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2144 entries, 0 to 2143
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   query_id             2144 non-null   object
 1   candidate_id         2144 non-null   object
 2   search_system        2144 non-null   object
 3   rank                 2144 non-null   int64
 4   score                2144 non-null   float64
 5   latency_to_first_ms  2144 non-null   int64
 6   latency_ms           2144 non-null   int64
 7   retrieved_at         2144 non-null   object
dtypes: float64(1), int64(3), object(4)
memory usage: 134.1+ KB

In [45]:
retrieval_vector.columns

Index(['query_id', 'candidate_id', 'search_system', 'rank', 'score',
       'latency_ms', 'retrieved_at'],
      dtype='object')

In [46]:
bm25.columns

Index(['Unnamed: 0', 'query_id', 'candidate_id', 'search_system', 'rank',
       'score', 'latency_ms', 'retrieved_at'],
      dtype='object')

In [47]:
sql_hr_bigger.columns

Index(['query_id', 'candidate_id', 'search_system', 'rank', 'score',
       'latency_to_first_ms', 'latency_ms', 'retrieved_at'],
      dtype='object')

In [48]:
sql_hr_cols = sql_hr_bigger[[
    'query_id',
    'candidate_id',
    'search_system',
    'rank',
    'score',
    'latency_to_first_ms',
    'latency_ms',
    'retrieved_at'
    ]]

In [49]:
sql_hr_cols.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2144 entries, 0 to 2143
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   query_id             2144 non-null   object
 1   candidate_id         2144 non-null   object
 2   search_system        2144 non-null   object
 3   rank                 2144 non-null   int64
 4   score                2144 non-null   float64
 5   latency_to_first_ms  2144 non-null   int64
 6   latency_ms           2144 non-null   int64
 7   retrieved_at         2144 non-null   object
dtypes: float64(1), int64(3), object(4)
memory usage: 134.1+ KB

In [50]:
retrieval_vector.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2400 entries, 0 to 2399
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   query_id       2400 non-null   object
 1   candidate_id   2400 non-null   object
 2   search_system  2400 non-null   object
 3   rank           2400 non-null   int64
 4   score          2400 non-null   float64
 5   latency_ms     2400 non-null   float64
 6   retrieved_at   2400 non-null   object
dtypes: float64(2), int64(1), object(4)
memory usage: 131.4+ KB

In [51]:
bm25.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2400 entries, 0 to 2399
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     2400 non-null   int64
 1   query_id       2400 non-null   object
 2   candidate_id   2400 non-null   object
 3   search_system  2400 non-null   object
 4   rank           2400 non-null   int64
 5   score          2400 non-null   float64
 6   latency_ms     2400 non-null   float64
 7   retrieved_at   2400 non-null   object
dtypes: float64(2), int64(2), object(4)
memory usage: 150.1+ KB

In [53]:
sql_hr_cols[150:155]

,query_id,candidate_id,search_system,rank,score,latency_to_first_ms,latency_ms,retrieved_at
150,Q_00011,C_44277,sql_hr_big,1,3.519858,18147,30217,2026-04-25T23:54:52.342816+00:00
151,Q_00011,C_17927,sql_hr_big,2,3.418370,18147,30217,2026-04-25T23:54:52.342816+00:00
152,Q_00011,C_16889,sql_hr_big,3,3.414067,18147,30217,2026-04-25T23:54:52.342816+00:00
153,Q_00011,C_12807,sql_hr_big,4,3.318096,18147,30217,2026-04-25T23:54:52.342816+00:00
154,Q_00011,C_06873,sql_hr_big,5,3.177271,18147,30217,2026-04-25T23:54:52.342816+00:00

In [54]:
queries = pd.read_csv('prepared/queries.csv')
candidates = pd.read_csv('raw/candidates.csv')

In [55]:
queries[queries['query_id'] == 'Q_00011'].head()

,query_id,vacancy_id,job_title,domain,query_type,query_text
10,Q_00011,VAC_0011,QA-инженер/Платежный сервис,qa,strict,"QA-инженер, опыт 3-6 лет, высшее образование/с..."

In [56]:
candidates[candidates['candidate_id'] == 'C_44277']

,candidate_id,sex,age,expected_salary_rub,desired_position,city,ready_to_relocate,ready_for_business_trips,employment_type,work_schedule,work_experience,work_experience_years,last_company,last_job_title,education_level_and_university,resume_updated_at,has_car
44276,C_44277,Мужчина,39,40000,Тестировщик ПО\ QA Junior,Москва,True,True,"стажировка, частичная занятость, проектная раб...","гибкий график, полный день, сменный график, уд...",Опыт работы 14 лет 6 месяцев Тестировщик ПО\ ...,14.5,"ЦКО ""Специалист"" при МГТУ им. Баумана",Тестировщик ПО,"Высшее образование 2019 ЦКО ""Специалист"" при М...",2019-04-26 15:30:00,False

In [33]:
sql_hr_cols['search_system'] = 'sql_hr_big'

In [34]:
sql_hr_cols.head(2)

,query_id,candidate_id,search_system,rank,score,latency_to_first_ms,latency_ms,retrieved_at
0,Q_00001,C_41343,sql_hr_big,1,5.826063,15152,23977,2026-04-25T23:51:24.815285+00:00
1,Q_00001,C_10206,sql_hr_big,2,5.796309,15152,23977,2026-04-25T23:51:24.815285+00:00

In [35]:
sql_hr_cols.to_csv('sql-hr/retrieval_sql_hr_bigger_llm_new.csv', index=False)

In [41]:
queries[queries['query_id'] == 'Q_00008']

,query_id,vacancy_id,job_title,domain,query_type,query_text
7,Q_00008,VAC_0008,Backend-разработчик (Java/Kotlin),backend,strict,"Backend-разработчик (Java/Kotlin), опыт 3-6 ле..."

In [42]:
candidates[candidates['candidate_id'] == 'C_18361']

,candidate_id,sex,age,expected_salary_rub,desired_position,city,ready_to_relocate,ready_for_business_trips,employment_type,work_schedule,work_experience,work_experience_years,last_company,last_job_title,education_level_and_university,resume_updated_at,has_car
18360,C_18361,Мужчина,34,85000,Backend разработчик (PHP),Санкт-Петербург,True,True,полная занятость,полный день,Опыт работы 6 лет 7 месяцев Август 2018 — по ...,6.583333,Уникальные Технологии,Backend-разработчик (PHP),Высшее образование 2006 Санкт-Петербургский го...,2019-05-07 17:08:00,False

In [23]:
sql_hr[sql_hr['query_id'] == 'Q_00008']

,query_id,candidate_id,search_system,rank,score,latency_to_first_ms,latency_ms,retrieved_at
94,Q_00008,C_05390,sql_hr,1,5.360648,49597,129015,2026-04-02T21:45:15.621914+00:00
95,Q_00008,C_18361,sql_hr,2,5.232892,49597,129015,2026-04-02T21:45:15.621914+00:00
96,Q_00008,C_13564,sql_hr,3,4.790746,49597,129015,2026-04-02T21:45:15.621914+00:00
97,Q_00008,C_19292,sql_hr,4,4.761497,49597,129015,2026-04-02T21:45:15.621914+00:00
98,Q_00008,C_08927,sql_hr,5,4.552195,49597,129015,2026-04-02T21:45:15.621914+00:00
99,Q_00008,C_03634,sql_hr,6,4.546404,49597,129015,2026-04-02T21:45:15.621914+00:00
100,Q_00008,C_12363,sql_hr,7,4.284947,49597,129015,2026-04-02T21:45:15.621914+00:00
101,Q_00008,C_18527,sql_hr,8,4.117008,49597,129015,2026-04-02T21:45:15.621914+00:00
102,Q_00008,C_23202,sql_hr,9,4.077612,49597,129015,2026-04-02T21:45:15.621914+00:00
103,Q_00008,C_03202,sql_hr,10,4.065489,49597,129015,2026-04-02T21:45:15.621914+00:00
104,Q_00008,C_12426,sql_hr,11,4.028575,49597,129015,2026-04-02T21:45:15.621914+00:00
105,Q_00008,C_24236,sql_hr,12,3.792846,49597,129015,2026-04-02T21:45:15.621914+00:00
106,Q_00008,C_14428,sql_hr,13,3.706415,49597,129015,2026-04-02T21:45:15.621914+00:00
107,Q_00008,C_28452,sql_hr,14,3.648914,49597,129015,2026-04-02T21:45:15.621914+00:00
108,Q_00008,C_18212,sql_hr,15,3.505267,49597,129015,2026-04-02T21:45:15.621914+00:00

In [57]:
sql_hr_cols.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2144 entries, 0 to 2143
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   query_id             2144 non-null   object
 1   candidate_id         2144 non-null   object
 2   search_system        2144 non-null   object
 3   rank                 2144 non-null   int64
 4   score                2144 non-null   float64
 5   latency_to_first_ms  2144 non-null   int64
 6   latency_ms           2144 non-null   int64
 7   retrieved_at         2144 non-null   object
dtypes: float64(1), int64(3), object(4)
memory usage: 134.1+ KB